<!--  #include file = "common.asp" -->
<!--  #include file = "common-client.asp" -->
<HTML>
<HEAD>
</HEAD>
<BODY>
 <h1> Invoice Merge Tool </h1>
 <P>
  *SJ* Write some blurb
 </P>
<CENTER>
<TABLE>
<TR><TD>
</TABLE>

<TABLE BORDER=3>
<TR> <TD> Status: </TD> <TD> <Div id='tgtStatus'/> </TD> </TR>
<TR> <TD> Results: </TD> <TD> <Div id='tgtResults'/> </TD> </TR>
<TR> <TD> Errors: </TD> <TD> <Div id='tgtErrors'/> </TD> </TR>
</TABLE>

</CENTER>
</BODY>
</HTML>

<script language="VBScript">
tgtStatus.innerText = "Waiting for instructions"

</script>
